import test from 'node:test';import assert from 'node:assert/strict';import {ACADEMY_URL,academyChild,addCandidates,prioritizeResources} from '../src/discovery.js';import {Autopilot} from '../src/autopilot.js';
test('Academy resources outrank other resources, videos last within each group',()=>{const q=[{title:'Other read'},{title:'Academy video',academy:true},{title:'Other video'},{title:'Academy read',academy:true}];assert.deepEqual(prioritizeResources(q).map(i=>i.title),['Academy read','Academy video','Other read','Other video']);});
test('Academy crawl follows unlocked program collections but excludes related and other programs',()=>{const a={url:'https://salescoach.apple.com/home/collection/235252',title:'Mac'};assert.ok(academyChild(a));assert.ok(academyChild({url:ACADEMY_URL,title:'Fokusera'}));for(const x of [{...a,related:true},{...a,locked:true},{...a,title:'Back'},{...a,url:'https://salescoach.apple.com/home/program/999/1'}])assert.equal(academyChild(x),false);});
test('A shared resource is upgraded to Academy priority without duplication',()=>{const q=[];const a={url:'https://salescoach.apple.com/home/content/view/1',kind:'resource',title:'A'};addCandidates(q,[a],'outside');addCandidates(q,[a],'academy',true);assert.equal(q.length,1);assert.equal(q[0].academy,true);assert.deepEqual(q[0].parents,['outside','academy']);});
test('Mixed queue cannot bypass the program completion gate',async()=>{const p=new Autopilot({api:{},report:()=>{}});await assert.rejects(p.processQueue([{academy:true},{}],async()=>{}),/separata/);});
test('New Academy material is searched before general discovery starts',async()=>{const phases=[];const api={tabs:{query:async()=>[{id:1,url:'https://salescoach.apple.com/home/for-you'}]},storage:{local:{set:async()=>{}}}};const p=new Autopilot({api,report:()=>{},onPage:()=>{}});let round=0;p.crawlCatalog=async(q,pages,publish,academy)=>{phases.push(academy?'academy discovery':'other discovery');if(academy)p.academyAudit={rootComplete:round>0,blocked:[]};if(academy&&round++===0)q.push({academy:true,status:'Hittad'});};p.processQueue=async q=>{phases.push('run '+(q[0]?.academy?'academy':'other'));q.forEach(i=>i.status='Registrerad klar')};await p.discoverAndRun();assert.deepEqual(phases,['academy discovery','run academy','academy discovery','other discovery','run other']);});

function gated({rootComplete=false,blocked=[],pending=false}={}){const visits=[];const p=new Autopilot({api:{tabs:{query:async()=>[{id:1,url:ACADEMY_URL}]},storage:{local:{set:async()=>{}}}},report:()=>{}});p.crawlCatalog=async(q,pages,publish,academy)=>{visits.push(academy?'academy':'other');p.academyAudit={rootComplete,blocked};if(pending&&!q.length)q.push({academy:true,status:'Hittad'});};p.processQueue=async q=>q.forEach(i=>i.status='Behöver hjälp');return {p,visits};}
test('Empty discovered queue is not proof that the whole Academy is complete',async()=>{const {p,visits}=gated();await p.discoverAndRun();assert.deepEqual(visits,['academy','other']);});
test('A failed Academy task allows outside resources after the Academy attempt',async()=>{const {p,visits}=gated({rootComplete:true,pending:true});await p.discoverAndRun();assert.ok(visits.includes('other'));});
test('Locked or inaccessible branches allow other resources',async()=>{const {p,visits}=gated({rootComplete:true,blocked:['Låst nivå']});await p.discoverAndRun();assert.ok(visits.includes('other'));});
test('Verified complete Academy permits outside resources',async()=>{const {p,visits}=gated({rootComplete:true});await p.discoverAndRun();assert.deepEqual(visits,['academy','other']);});
test('Blocked Academy remains visible and is never reported complete while other work runs',async()=>{const {p,visits}=gated({blocked:['Resurser 5']});const saved={},messages=[];p.api.storage.local.set=async value=>Object.assign(saved,value);p.report=m=>messages.push(m);await p.discoverAndRun();assert.match(saved.academyNotice,/Resurser 5/);assert.ok(visits.includes('other'));assert.ok(!messages.some(m=>m==='Alla Academy-krav är verifierade som klara.'));});
