import test from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {courseFrame,validateAnswer,Autopilot} from '../src/autopilot.js';
const url='https://salescoach.apple.com/home/content/view/123';
const lesson='MDM gör att organisationen kan konfigurera och hantera sina enheter centralt.';
function page(html,pageURL=url){const dom=new JSDOM(html,{url:pageURL});global.document=dom.window.document;global.location=dom.window.location;global.getComputedStyle=dom.window.getComputedStyle;global.Event=dom.window.Event;dom.window.HTMLElement.prototype.getClientRects=function(){return this.hidden?[]:[{}]};dom.window.HTMLElement.prototype.scrollIntoView=function(){};return dom;}
function quiz(multi=false){page(`<main><fieldset><legend>Vad används MDM till?</legend><label><input type="${multi?'checkbox':'radio'}" name="q">Hantera enheter</label><label><input type="${multi?'checkbox':'radio'}" name="q">Ladda batteriet</label></fieldset><button id="submit">Skicka svar</button></main>`);}
test('Continues through five distinct submissions and stops at 100 percent',async()=>{
 page('<main><fieldset><legend>Vilket alternativ stöds av kursen?</legend>'+Array.from({length:6},(_,i)=>'<label><input type="radio" name="q">Alternativ '+(i+1)+'</label>').join('')+'</fieldset><button id="submit">Skicka svar</button></main>');let submissions=0,retries=0,analyses=0;
 document.querySelector('#submit').onclick=()=>{submissions++;document.querySelector('fieldset').disabled=true;document.querySelector('#submit').disabled=true;document.querySelector('main').insertAdjacentHTML('beforeend','<div id="result">'+(submissions===5?100:submissions*20)+' % Bra jobbat!</div>'+(submissions<5?'<button id="retry">Försök igen</button>':''));if(submissions<5)document.querySelector('#retry').onclick=()=>{retries++;document.querySelector('#result').remove();document.querySelector('#retry').remove();document.querySelector('fieldset').disabled=false;document.querySelector('#submit').disabled=false;document.querySelectorAll('input').forEach(e=>e.checked=false);};};
 const {pilot}=runner(async()=>({ok:true,text:JSON.stringify({answers:[++analyses],uncertain:false,evidence:lesson})}));pilot.prepareTest=async()=>{};assert.equal(await pilot.resource(),'passed');assert.equal(submissions,5);assert.equal(retries,4);assert.equal(analyses,5);
});
const response=JSON.stringify({answers:[1],uncertain:false,evidence:lesson,reason:'Enhetshantering'});
test('Full quiz loop submits, observes failure despite XP, re-analyzes and passes',async()=>{
 quiz();let submissions=0,retries=0;const requests=[];
 document.querySelector('#submit').onclick=()=>{submissions++;document.querySelector('fieldset').disabled=true;document.querySelector('#submit').disabled=true;document.querySelector('main').insertAdjacentHTML('beforeend',submissions===1?'<div id="result">0 % Gå igenom dina svar och försök igen.</div><button id="retry">Försök igen</button><a id="xp" aria-label="+3 INTJÄNADE ERFARENHETSPOÄNG">XP</a>':'<div id="result">100 % Bra jobbat!</div>');if(submissions===1)document.querySelector('#retry').onclick=()=>{retries++;document.querySelector('#result').remove();document.querySelector('#xp').remove();document.querySelector('#retry').remove();document.querySelector('fieldset').disabled=false;document.querySelector('#submit').disabled=false;document.querySelectorAll('input').forEach(e=>e.checked=false);};};
 const {pilot}=runner(async request=>{requests.push(request);return {ok:true,text:JSON.stringify({answers:[requests.length===1?2:1],uncertain:false,evidence:lesson})};});
 pilot.prepareTest=async()=>{};assert.equal(await pilot.resource(),'passed');assert.equal(submissions,2);assert.equal(retries,1);assert.match(requests[1].question,/Ladda batteriet.*0 %/);assert.equal(courseFrame().score,100);
});
test('Result view with changed question markup and cleared selections retries the original submission',async()=>{
 quiz();let submissions=0;const requests=[];const original=document.querySelector('legend').textContent;
 document.querySelector('#submit').onclick=()=>{
  submissions++;document.querySelector('fieldset').disabled=true;document.querySelector('#submit').disabled=true;
  document.querySelector('legend').textContent='Resultat: '+original;
  document.querySelectorAll('input').forEach(e=>e.checked=false);
  document.querySelector('main').insertAdjacentHTML('beforeend',submissions===1?'<div id="result">50 % Gå igenom dina svar.</div><button id="retry">Försök igen</button>':'<div id="result">100 % Bra jobbat!</div>');
  if(submissions===1)document.querySelector('#retry').onclick=()=>{document.querySelector('#result').remove();document.querySelector('#retry').remove();document.querySelector('legend').textContent=original;document.querySelector('fieldset').disabled=false;document.querySelector('#submit').disabled=false;};
 };
 const {pilot}=runner(async request=>{requests.push(request);return {ok:true,text:JSON.stringify({answers:[requests.length===1?2:1],uncertain:false,evidence:lesson})};});
 pilot.prepareTest=async()=>{};
 assert.equal(await pilot.resource(),'passed');assert.equal(submissions,2);assert.equal(requests.length,2);
 assert.match(requests[1].question,/Ladda batteriet.*50 %/);
});
test('67 percent with XP uses question feedback and re-analyzes a repeated wrong answer before submitting',async()=>{
 quiz();let submissions=0;const requests=[];
 document.querySelector('#submit').onclick=()=>{
  submissions++;document.querySelector('fieldset').disabled=true;document.querySelector('#submit').disabled=true;
  document.querySelector('main').insertAdjacentHTML('beforeend',submissions===1?'<div id="result">67 % Bra jobbat!</div><button id="retry">Försök igen</button><a id="xp" aria-label="+3 INTJÄNADE ERFARENHETSPOÄNG">XP</a>':'<div id="result">100 % Bra jobbat!</div>');
  if(submissions===1){document.querySelector('fieldset').insertAdjacentHTML('beforeend','<p class="feedback">Fel svar. MDM handlar om hantering av enheter.</p>');document.querySelector('#retry').onclick=()=>{document.querySelector('#result').remove();document.querySelector('#retry').remove();document.querySelector('#xp').remove();document.querySelector('.feedback').remove();document.querySelector('fieldset').disabled=false;document.querySelector('#submit').disabled=false;document.querySelectorAll('input').forEach(e=>e.checked=false);};}
 };
 const {pilot}=runner(async request=>{requests.push(request);return {ok:true,text:JSON.stringify({answers:[requests.length<3?2:1],uncertain:false,evidence:lesson})};});pilot.prepareTest=async()=>{};
 assert.equal(await pilot.resource(),'passed');assert.equal(submissions,2);assert.equal(requests.length,3);
 assert.match(requests[1].question,/67 %/);assert.match(requests[1].question,/Fel svar. MDM handlar/);assert.match(requests[2].question,/Förra AI-analysen/);
});
test('Shuffling choices cannot resubmit the same rejected answer',async()=>{
 quiz();let submissions=0;document.querySelector('#submit').onclick=()=>submissions++;const {pilot}=runner(async()=>({ok:true,text:response}));const before=courseFrame();pilot.failedAttempts.set(pilot.testKey(before),[{ids:[2],score:0,signature:pilot.answerSignature(before,[2]),choices:['Ladda batteriet']}]);const labels=document.querySelectorAll('label');labels[0].parentElement.appendChild(labels[0]);const after=courseFrame();assert.equal(pilot.testKey(before),pilot.testKey(after));await assert.rejects(pilot.solve({frameId:0,result:after}),/redan underkänt/);assert.equal(submissions,0);
});
test('Retry budget remains bounded when the failed result has no selected answers',async()=>{
 const {pilot}=runner(async()=>({ok:false}));let retries=0,stage=0;pilot.prepareTest=async()=>{};pilot.frames=async()=>[{frameId:0,result:{fingerprint:'changing-'+stage,options:[{id:1,text:'A',disabled:false},{id:2,text:'B',disabled:false}],groups:1,score:stage%2===0?0:null,retry:stage%2===0,lesson:'',sections:[],next:[]}}];pilot.act=async()=>{retries++;stage++;};pilot.solve=async()=>{stage++;};await assert.rejects(pilot.resource(),/Gränsen på 5/);assert.equal(retries,4);
});
test('Reads labelled native answers and submits only matching checked choices',()=>{quiz();let submitted=0;document.querySelector('#submit').onclick=()=>submitted++;let s=courseFrame();assert.equal(s.prompt,'Vad används MDM till?');assert.equal(s.options[0].text,'Hantera enheter');assert.throws(()=>courseFrame({...s,action:'submit',ids:[1]}));courseFrame({...s,action:'select',id:1,text:s.options[0].text,selected:true});s=courseFrame();courseFrame({...s,action:'submit',ids:[1]});assert.equal(submitted,1);});
test('Hidden questions and ambiguous submit buttons are excluded',()=>{page('<main><fieldset hidden><label><input type="radio">Hidden</label></fieldset><button>Skicka svar</button><button>Skicka svar</button></main>');const s=courseFrame();assert.equal(s.options.length,0);assert.equal(s.submit,false);});
test('Only strict answers with actual source evidence are accepted',()=>{quiz();const s=courseFrame();assert.deepEqual(validateAnswer(response,s,lesson).ids,[1]);for(const bad of ['free prose',JSON.stringify({answers:[1],uncertain:true,evidence:lesson}),JSON.stringify({answers:[1,2],uncertain:false,evidence:lesson}),JSON.stringify({answers:[9],uncertain:false,evidence:lesson}),JSON.stringify({answers:[1],uncertain:false,evidence:'Ett helt påhittat citat som inte finns'})])assert.throws(()=>validateAnswer(bad,s,lesson));});
test('Checkbox answers allow multiple distinct valid options',()=>{quiz(true);const s=courseFrame();assert.deepEqual(validateAnswer(JSON.stringify({answers:[2,1],uncertain:false,evidence:lesson}),s,lesson).ids,[1,2]);assert.throws(()=>validateAnswer(JSON.stringify({answers:[1,1],uncertain:false,evidence:lesson}),s,lesson));});
function runner(native){const calls=[];const api={tabs:{get:async()=>({active:true,url})},scripting:{executeScript:async spec=>{calls.push(spec);return[{frameId:0,documentId:'doc',result:courseFrame(spec.args?.[0])}]}}};const pilot=new Autopilot({api,native,report:()=>{},onPage:()=>{},wait:async()=>{}});Object.assign(pilot,{tabId:1,expectedURL:url,context:lesson});pilot.reviewAnswer=async(state,context,question)=>{const reply=await native({action:'choose',context,question,optionCount:state.options.length,requiredCount:state.requiredCount});await pilot.guard();if(!reply.ok)throw new Error(reply.error||'AI-anropet misslyckades.');return validateAnswer(reply.text,state,context);};return {pilot,calls};}
test('Stop while AI is pending prevents both selection and submission',async()=>{quiz();let resolve;const {pilot,calls}=runner(()=>new Promise(r=>resolve=r));const task=pilot.solve({frameId:0,result:courseFrame()});await Promise.resolve();pilot.stop();resolve({ok:true,text:response});await assert.rejects(task,/Stoppad/);assert.equal(calls.length,0);});
test('End-to-end controller selects, submits and refuses a repeated question',async()=>{quiz();let count=0;document.querySelector('#submit').onclick=()=>count++;const {pilot}=runner(async()=>({ok:true,text:response}));await pilot.solve({frameId:0,result:courseFrame()});assert.equal(count,1);await assert.rejects(pilot.solve({frameId:0,result:courseFrame()}),/Samma fråga/);assert.equal(count,1);});
test('User navigation while AI runs prevents every write',async()=>{quiz();const {pilot,calls}=runner(async()=>{pilot.expectedURL=url+'/changed';return{ok:true,text:response}});await assert.rejects(pilot.solve({frameId:0,result:courseFrame()}),/bytte flik/);assert.equal(calls.filter(c=>c.args?.[0]?.action).length,0);});
test('Failed feedback and free text block submissions',()=>{quiz();document.querySelector('main').insertAdjacentHTML('beforeend','<p role="alert">Fel svar</p>');let s=courseFrame();assert.equal(s.failed,true);assert.throws(()=>courseFrame({...s,action:'submit',ids:[]}));quiz();document.querySelector('main').insertAdjacentHTML('beforeend','<textarea></textarea>');s=courseFrame();assert.equal(s.freeText,true);assert.throws(()=>courseFrame({...s,action:'submit',ids:[]}));});

test('Two visible question groups are detected as unsupported',()=>{quiz();document.querySelector('main').insertAdjacentHTML('beforeend','<fieldset><legend>Fråga två</legend><label><input type="radio" name="q2">Svar</label></fieldset>');assert.equal(courseFrame().groups,2);});
test('Source collection excludes the question and its options',()=>{quiz();document.querySelector('main').insertAdjacentHTML('afterbegin','<p>'+lesson+'</p>');const s=courseFrame();assert.equal(s.lesson,lesson);assert.doesNotMatch(s.lesson,/Ladda batteriet/);});

test('Canonical URL cleanup does not stop the same resource',async()=>{quiz();const {pilot}=runner(async()=>({ok:true,text:response}));pilot.expectedURL=url+'?backTo=collection';await pilot.guard();assert.equal(pilot.expectedURL,url);});
function batch(){page(`<main><p>${lesson}</p><div><div>1 Vad kan MDM göra? Välj 2.</div><label><input type="checkbox">Hantera enheter</label><label><input type="checkbox">Distribuera appar</label><label><input type="checkbox">Koka kaffe</label></div><div><div>2 Vad används MDM till? Välj ett.</div><label><input type="radio" name="b">Konfigurera enheter</label><label><input type="radio" name="b">Ladda batterier</label></div><button id="submit">Skicka</button></main>`);}
test('Batch generic containers preserve independent counts and exclude question text from evidence',()=>{batch();const s=courseFrame();assert.equal(s.groups,2);assert.equal(s.questions[0].requiredCount,2);assert.equal(s.questions[1].requiredCount,1);assert.deepEqual(s.questions[1].options.map(o=>o.id),[4,5]);assert.equal(s.lesson,lesson);assert.throws(()=>validateAnswer(response,s.questions[0],lesson));});
test('Entire test is validated before selection and submitted exactly once',async()=>{batch();let count=0;document.querySelector('#submit').onclick=()=>count++;let n=0;const {pilot}=runner(async()=>({ok:true,text:JSON.stringify({answers:++n===1?[1,2]:[1],uncertain:false,evidence:lesson})}));await pilot.solve({frameId:0,result:courseFrame()});assert.equal(n,2);assert.equal(count,1);assert.deepEqual(courseFrame().options.filter(o=>o.selected).map(o=>o.id),[1,2,4]);});
test('Retry history keeps identical option labels in separate questions',async()=>{batch();document.querySelector('input[name="b"]').parentElement.lastChild.textContent='Hantera enheter';const s=courseFrame(),requests=[];const {pilot}=runner(async request=>{requests.push(request);return {ok:true,text:JSON.stringify({answers:requests.length===1?[1,2]:[1],uncertain:false,evidence:lesson})};});pilot.failedAttempts.set(pilot.testKey(s),[{ids:[1,2,5],score:50,choices:['Hantera enheter','Distribuera appar','Ladda batterier'],questionChoices:pilot.questionChoices(s,[1,2,5])}]);await pilot.solve({frameId:0,result:s});assert.match(requests[1].question,/den här frågan hade 2 och/);assert.doesNotMatch(requests[1].question,/den här frågan hade 1\+2/);});
test('Batch re-analysis receives feedback for the corresponding question and remains bounded',async()=>{batch();let count=0;document.querySelector('#submit').onclick=()=>count++;const requests=[];const {pilot}=runner(async request=>{requests.push(request);return {ok:true,text:JSON.stringify({answers:requests.length%2?[1,2]:[1],uncertain:false,evidence:lesson})};});const s=courseFrame();pilot.failedAttempts.set(pilot.testKey(s),[{ids:[1,2,4],score:67,signature:pilot.answerSignature(s,[1,2,4]),feedback:[{prompt:s.questions[0].prompt,feedback:'Fel svar på första frågan'}]}]);await assert.rejects(pilot.solve({frameId:0,result:s}),/fördjupad analys/);assert.equal(requests.length,10);assert.match(requests[0].question,/Fel svar på första frågan/);assert.doesNotMatch(requests[1].question,/Fel svar på första frågan/);assert.equal(count,0);});
test('An uncertain later answer leaves all questions unchanged',async()=>{batch();let n=0;const {pilot}=runner(async()=>({ok:true,text:JSON.stringify({answers:[1,2],uncertain:++n===2,evidence:lesson})}));await assert.rejects(pilot.solve({frameId:0,result:courseFrame()}));assert.equal(courseFrame().options.some(o=>o.selected),false);});
test('Batch submit rejects an unanswered question even when selected ids match',()=>{batch();let s=courseFrame();courseFrame({...s,action:'select',id:1,text:s.options[0].text,selected:true});s=courseFrame();assert.throws(()=>courseFrame({...s,action:'submit',ids:[1]}));});
test('Knowledge test resolves its collection when Sales Coach removes backTo',async()=>{
 const {pilot}=runner(async()=>({ok:false}));const sourceURL='https://salescoach.apple.com/home/content/view/456';const collection='https://salescoach.apple.com/home/collection/99';const visits=[];
 pilot.navigate=async target=>{visits.push(target);pilot.expectedURL=target;};pilot.guard=async()=>{};
 pilot.crawlCatalog=async queue=>queue.push({key:new URL(url).pathname,parents:[collection]});
 pilot.inventory=async()=>({items:[{url:sourceURL,completed:true,locked:false},{url,locked:false}]});
 pilot.frames=async()=>[{frameId:0,result:{groups:pilot.expectedURL===url?2:0,options:[],freeText:false,lesson:lesson.repeat(10),sections:[]}}];
 await pilot.prepareTest();assert.deepEqual(visits,[collection,sourceURL,url]);assert.ok(pilot.context.includes(lesson));assert.equal(pilot.expectedURL,url);
});
test('Test uses known collection ancestry and refuses a collection with no readable source',async()=>{
 const {pilot}=runner(async()=>({ok:false}));const collection='https://salescoach.apple.com/home/collection/99';pilot.testParents=[collection];pilot.navigate=async target=>{pilot.expectedURL=target;};pilot.guard=async()=>{};pilot.crawlCatalog=async()=>{throw new Error('Must not rediscover known parent');};pilot.inventory=async()=>({items:[]});
 await assert.rejects(pilot.prepareTest(),/För lite kursunderlag/);assert.equal(pilot.expectedURL,url);assert.equal(pilot.context,lesson);
});
test('Late arriving quiz always loads its course sources before answering',async()=>{
 const {pilot}=runner(async()=>({ok:false}));let calls=0,prepared=false,solved=false;
 pilot.frames=async()=>[{frameId:0,result:++calls===1?{options:[],lesson:'Introduction',sections:[],next:[]} : solved?{options:[],lesson:'',sections:[],next:[],complete:true}:{options:[{id:1},{id:2}],groups:2,lesson:'',sections:[],next:[]}}];
 pilot.prepareTest=async()=>{prepared=true;};pilot.solve=async()=>{assert.equal(prepared,true);solved=true;};
 await pilot.resource();assert.equal(solved,true);
});
test('True/false question without choose instructions stays a separate group',()=>{
 batch();document.querySelector('#submit').insertAdjacentHTML('beforebegin','<div><div>3 Sant eller falskt. MDM hanterar enheter.</div><div><label><input type="radio" name="true">Rätt</label><label><input type="radio" name="true">Falskt</label></div></div>');
 const s=courseFrame();assert.equal(s.groups,3);assert.equal(s.questions[2].prompt,'3 Sant eller falskt. MDM hanterar enheter.');assert.deepEqual(s.questions[2].options.map(o=>o.text),['Rätt','Falskt']);
});
test('Selection counter after the options does not invalidate a stable test',()=>{batch();const s=courseFrame();document.querySelector('#submit').insertAdjacentHTML('beforebegin','<p>1 av 3 alternativ valda</p>');assert.equal(courseFrame().fingerprint,s.fingerprint);});
test('Indexed source references resolve to original text and unknown references are rejected',()=>{quiz();const s=courseFrame(),context='KÄLLOR MED ID\n[K1] '+lesson;const answer={answers:[1],uncertain:false,sourceIds:[1]};assert.equal(validateAnswer(JSON.stringify(answer),s,context).evidence,lesson);for(const sourceIds of [[2],[],['1']])assert.throws(()=>validateAnswer(JSON.stringify({...answer,sourceIds}),s,context));});
test('Sales Coach live selection count keeps question identity and exact answer count',()=>{batch();const before=courseFrame();const heading=document.querySelector('main > div > div');heading.textContent='1 Vad kan MDM göra? Du har valt 1 av 2.';const after=courseFrame();assert.equal(after.fingerprint,before.fingerprint);assert.equal(after.questions[0].requiredCount,2);});
test('Apple percentage feedback is recognized with inherited disabled controls',()=>{quiz();document.querySelector('fieldset').disabled=true;document.querySelector('#submit').remove();document.querySelector('main').insertAdjacentHTML('beforeend','<p>100 %</p><p>Bra jobbat!</p><button>Försök igen</button>');const s=courseFrame();assert.equal(s.score,100);assert.equal(s.complete,true);assert.equal(s.options.every(o=>o.disabled),true);});
test('Apple failed percentage exposes one safe retry action',()=>{quiz();document.querySelector('fieldset').disabled=true;document.querySelector('#submit').remove();document.querySelector('main').insertAdjacentHTML('beforeend','<div>33 % Gå igenom dina svar och försök igen.</div><button id="retry">Försök igen</button>');let retried=0;document.querySelector('#retry').onclick=()=>retried++;const s=courseFrame();assert.equal(s.score,33);assert.equal(s.retry,true);courseFrame({...s,action:'retry'});assert.equal(retried,1);});
test('Unrelated percentages are not mistaken for quiz results',()=>{quiz();document.querySelector('main').insertAdjacentHTML('afterbegin','<p>60 % av marknaden använder AI.</p>');assert.equal(courseFrame().score,null);});
test('A submitted test waits for the server result instead of solving or submitting twice',async()=>{const {pilot}=runner(async()=>({ok:false}));let reads=0,solves=0;const question={groups:2,options:[{id:1},{id:2}],fingerprint:'pending',lesson:'',sections:[],next:[]};pilot.prepareTest=async()=>{};pilot.frames=async()=>[{frameId:0,result:++reads>=4?{options:[],score:100,lesson:'',sections:[],next:[]}:question}];pilot.solve=async()=>{solves++;pilot.submitted.add(url+'|pending');};assert.equal(await pilot.resource(),'passed');assert.equal(solves,1);});
test('A failed score opens one retry before preparing a new assisted attempt',async()=>{const {pilot}=runner(async()=>({ok:false}));let stage=0,retries=0,solves=0;const base={fingerprint:'retry-me',lesson:'',sections:[],next:[],questions:[],groups:1,freeText:false,failed:false,passed:false,complete:false};pilot.frames=async()=>[{frameId:0,result:stage===0?{...base,score:33,retry:true,submit:false,options:[{id:1,selected:false,disabled:true},{id:2,selected:true,disabled:true}]}:stage===1?{...base,score:null,retry:false,submit:true,options:[{id:1,selected:false,disabled:false},{id:2,selected:false,disabled:false}]}:{...base,score:100,retry:false,options:[]}}];pilot.act=async(_frame,action)=>{assert.equal(action,'retry');retries++;stage=1;};pilot.prepareTest=async()=>{};pilot.solve=async()=>{solves++;stage=2;};assert.equal(await pilot.resource(),'passed');assert.equal(retries,1);assert.equal(solves,1);assert.deepEqual(pilot.failedAttempts.get(url+'|retry-me').map(({ids,score})=>({ids,score})),[{ids:[2],score:33}]);});
test('A stale failed result frame cannot click Try again twice',async()=>{const {pilot}=runner(async()=>({ok:false}));let reads=0,retries=0,solves=0,done=false;const base={fingerprint:'stale-retry',lesson:'',sections:[],next:[],questions:[],groups:1,freeText:false,failed:false,passed:false,complete:false};pilot.frames=async()=>[{frameId:0,result:done?{...base,score:100,options:[]}:(reads++<3?{...base,score:0,retry:true,options:[{id:1,selected:true,disabled:true},{id:2,selected:false,disabled:true}]}:{...base,score:null,retry:false,submit:true,options:[{id:1,selected:false,disabled:false},{id:2,selected:false,disabled:false}]})}];pilot.act=async(_frame,action)=>{assert.equal(action,'retry');retries++;};pilot.prepareTest=async()=>{};pilot.solve=async()=>{solves++;done=true;};assert.equal(await pilot.resource(),'passed');assert.equal(retries,1);assert.equal(solves,1);});
test('Perfect score is recognized when Apple removes the retry button',()=>{quiz();document.querySelector('fieldset').disabled=true;document.querySelector('#submit').remove();document.querySelector('main').insertAdjacentHTML('beforeend','<p>100 %</p><p>Bra jobbat!</p>');assert.equal(courseFrame().score,100);});

test('Result remains detectable when a disabled submit control remains in the DOM',()=>{quiz();document.querySelector('fieldset').disabled=true;document.querySelector('#submit').disabled=true;document.querySelector('main').insertAdjacentHTML('afterbegin','<div>100 % Bra jobbat!</div>');assert.equal(courseFrame().score,100);});

test('Apple renders the percent sign with CSS and a different accessible success label',()=>{quiz();document.querySelector('fieldset').disabled=true;document.querySelector('#submit').remove();document.querySelector('main').insertAdjacentHTML('beforeend','<div aria-label="100% Bra jobbat!"><span>100</span><span>Du fick ett perfekt resultat!</span></div>');assert.equal(courseFrame().score,100);});
test('Earned experience points are an explicit completion signal',()=>{page('<main><a aria-label="+20 INTJÄNADE ERFARENHETSPOÄNG 20XP • Full pott!">Belöning</a></main>');const s=courseFrame();assert.equal(s.xp,20);assert.equal(s.success,false);assert.equal(s.complete,true);});
test('An XP toast naming a previous resource cannot complete the current page',()=>{const dom=page('<main><a aria-label=\'+20 INTJÄNADE ERFARENHETSPOÄNG 20XP • Full pott! "Gammal kurs"\'>Belöning</a></main>');dom.window.document.title='Ny kurs | Apple Sales Coach';const s=courseFrame();assert.equal(s.xp,0);assert.equal(s.complete,false);});
test('Safe course interactions include unopened controls and tabs but exclude navigation and media',()=>{page('<main><button id="open" aria-expanded="false">Avsnitt</button><button role="tab" aria-selected="false">Exempel 2</button><button>Visa mer</button><button>Visa åtgärder</button><button>Spela upp video</button><button>Stäng</button></main>');const s=courseFrame();assert.deepEqual(s.interactions.map(i=>i.text),['Avsnitt','Exempel 2','Visa mer']);let clicked=0;document.querySelector('[role="tab"]').onclick=()=>clicked++;const tab=s.interactions.find(i=>i.text==='Exempel 2');courseFrame({...s,action:'interact',...tab});assert.equal(clicked,1);});
test('Apple embedded course frames expose custom activity buttons but still exclude media controls',()=>{page('<main><button>Scenario A</button><button>Inställningar</button><button>Spela upp video</button></main>','https://seeddownload.cdn-apple.com/course/index.html');assert.deepEqual(courseFrame().interactions.map(i=>i.text),['Scenario A']);});
test('Scrollable course content advances in bounded steps and reports remaining distance',()=>{page('<main><p>Kurs</p></main>');const root=document.documentElement;Object.defineProperties(root,{scrollHeight:{value:1800,configurable:true},clientHeight:{value:600,configurable:true},scrollTop:{value:0,writable:true,configurable:true}});let s=courseFrame();assert.deepEqual(s.scroll,[{id:1,top:0,remaining:1200}]);courseFrame({...s,action:'scroll',...s.scroll[0]});assert.equal(root.scrollTop,500);s=courseFrame();assert.equal(s.scroll[0].remaining,700);});
test('Multiple same-page Next controls can be addressed safely one at a time',()=>{page('<main><button id="first">Nästa</button><button id="second">Nästa</button></main>');let clicked='';document.querySelector('#first').onclick=()=>clicked='first';document.querySelector('#second').onclick=()=>clicked='second';const s=courseFrame();assert.equal(s.stepControls.length,2);assert.throws(()=>courseFrame({...s,action:'next',text:'Nästa'}));courseFrame({...s,action:'next',...s.stepControls[1]});assert.equal(clicked,'second');});

test('Repeated valid source references are deduplicated, not reported as missing',()=>{quiz();assert.equal(validateAnswer(JSON.stringify({answers:[1],uncertain:false,sourceIds:[1,1,1]}),courseFrame(),'KÄLLOR MED ID\n[K1] '+lesson).evidence,lesson);});
test('Source preparation retains current lesson and reads lessons alongside quizzes without submitting them',async()=>{
 const {pilot}=runner(async()=>({ok:false}));const collection='https://salescoach.apple.com/home/collection/99',sourceURL='https://salescoach.apple.com/home/content/view/456';
 pilot.context='Egen kurskälla. '.repeat(40);pilot.testParents=[collection];pilot.navigate=async target=>{pilot.expectedURL=target;};pilot.guard=async()=>{};pilot.inventory=async()=>({items:[{url:sourceURL}]});
 pilot.frames=async()=>[{frameId:0,result:{groups:2,options:[{text:'Quiz answer must not be a source'}],freeText:false,lesson:lesson.repeat(10),sections:[]}}];pilot.act=async()=>assert.fail('No quiz interaction while collecting sources');
 await pilot.prepareTest();assert.match(pilot.context,/Egen kurskälla/);assert.ok(pilot.context.includes(lesson));assert.doesNotMatch(pilot.context,/Quiz answer/);
});
