import test from 'node:test';import assert from 'node:assert/strict';import {JSDOM} from 'jsdom';
import {catalogPage,classifyCourse,addCandidates} from '../src/discovery.js';
import {Autopilot} from '../src/autopilot.js';
test('Finds open badges, resources and event courses, never external or earned badge routes',()=>{const d=new JSDOM('<a href="/home/achievements/unearned/2">Badge</a><a href="/home/achievements/earned/3">Done</a><a href="/home/content/view/4">Resource</a><a href="/home/course/35019">Workshop</a><a href="https://evil.example/home/course/5">External</a>',{url:'https://salescoach.apple.com/home/for-you'});global.document=d.window.document;global.location=d.window.location;d.window.HTMLElement.prototype.getClientRects=()=>[{}];assert.deepEqual(catalogPage().links.map(l=>l.kind),['badge','resource','resource']);});
test('Queue deduplicates across badges, preserves verification parents, ignores done/locked',()=>{const q=[];const r={url:'https://salescoach.apple.com/home/content/view/4?a=1',title:'A',kind:'resource'};addCandidates(q,[r,{...r,url:r.url.replace('/4','/5'),completed:true},{...r,url:r.url.replace('/4','/6'),locked:true}],'badge1');addCandidates(q,[{...r,url:r.url.replace('a=1','a=2')}],'badge2');assert.equal(q.length,1);assert.deepEqual(q[0].parents,['badge1','badge2']);});
test('Classifies supported work and skips unknown/free-text activities',()=>{assert.equal(classifyCourse([{result:{video:{}}}]).supported,true);assert.equal(classifyCourse([{result:{options:[{},{}]}}]).kind,'Flervalsfråga');assert.equal(classifyCourse([{result:{freeText:true,video:{}}}]).supported,false);assert.equal(classifyCourse([{result:{lesson:'short'}}]).supported,false);});
test('Event-gated course is reported as missing access',()=>{const result=classifyCourse([{result:{text:'Du får tillgång till de här kursuppgifterna när du har blivit inbjuden till eventet.'}}]);assert.equal(result.supported,false);assert.equal(result.code,'ACCESS_DENIED');assert.match(result.reason,/inbjudan/);});
test('Event-gated course tolerates spacing and alternate invitation wording',()=>{for(const text of ['Du får tillgång\u00a0till dessa kursuppgifter när du har fått en inbjudan till evenemanget.','Course materials become available when invited to the event.'])assert.equal(classifyCourse([{result:{text}}]).code,'ACCESS_DENIED');});
test('Discovery continues to the next resource when one is unsupported',async()=>{const urls=[];const base='https://salescoach.apple.com';let url=base+'/home/for-you';let state=[];const links=[{kind:'resource',url:base+'/home/content/view/1',title:'Unsupported'},{kind:'resource',url:base+'/home/content/view/2',title:'Reading'}];const api={tabs:{query:async()=>[{id:1,url}],get:async()=>({active:true,url})},storage:{local:{set:async()=>{}}},scripting:{executeScript:async()=>[{result:{links}}]}};const runner=new Autopilot({api,native:()=>{},report:()=>{},onPage:()=>{},onQueue:q=>state=q,wait:async()=>{}});runner.navigate=async u=>{url=u;runner.expectedURL=u;urls.push(u)};runner.inventory=async()=>({items:[]});runner.frames=async()=>[{result:{lesson:url.endsWith('/2')?'source '.repeat(40):''}}];let ran=0;runner.resource=async()=>ran++;await runner.discoverAndRun();assert.equal(ran,1);assert.equal(state[0].status,'Behöver hjälp');assert.equal(state[1].status,'Ej verifierad');assert.ok(urls.includes(links[1].url));});
test('A delayed invitation gate is awaited before an event course is processed',async()=>{const p=new Autopilot({api:{},report:()=>{},onStatus:()=>{},wait:async()=>{}}),item={url:'https://salescoach.apple.com/home/course/35183',title:'Business Upgrader'};p.sleep=async()=>{};let reads=0;p.frames=async()=>[{result:++reads<3?{lesson:'Beskrivning '.repeat(30)}:{text:'Du får tillgång till de här kursuppgifterna när du har blivit inbjuden till eventet.'}}];const settled=await p.settledCourseFrames(item,await p.frames());assert.equal(reads,3);assert.equal(classifyCourse(settled,item.title).code,'ACCESS_DENIED');});
test('Discovers and opens unearned badge buttons without guessing URLs',()=>{const d=new JSDOM('<button aria-label="Badge unearned">Badge</button><button>Old earned</button>',{url:'https://salescoach.apple.com/home/for-you'});global.document=d.window.document;global.location=d.window.location;d.window.HTMLElement.prototype.getClientRects=()=>[{}];let clicks=0;document.querySelector('button').onclick=()=>clicks++;const p=catalogPage();assert.equal(p.links.length,1);assert.equal(p.links[0].kind,'badgeButton');catalogPage({open:p.links[0].button});assert.equal(clicks,1);assert.throws(()=>catalogPage({open:'Old earned'}));});

test('Named forms never become reading resources before their fields load',()=>{const result=classifyCourse([{result:{lesson:'Introduction '.repeat(100)}}],'Årets lyckade exempel – formulär');assert.equal(result.supported,false);assert.match(result.reason,/egna uppgifter/);});
test('Locked program placeholders without URLs remain visible to the audit',()=>{const d=new JSDOM('<a role="link" aria-disabled="true">Resurser 4</a><a role="link" aria-disabled="true">Resurser 5</a>');global.document=d.window.document;global.location=d.window.location;d.window.HTMLElement.prototype.getClientRects=()=>[{}];assert.deepEqual(catalogPage().lockedItems,['Resurser 4','Resurser 5']);});
