import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyLedger,updateLedger,exhausted} from '../src/ledger.js';
import {Autopilot} from '../src/autopilot.js';
test('Attempt counts survive serialization; verification and history remain distinct',()=>{let db=emptyLedger();const item={key:'/home/content/view/1',title:'One',status:'Behöver hjälp'};for(let i=0;i<3;i++){updateLedger(db,item,{attempt:true});db=JSON.parse(JSON.stringify(db));}assert.equal(exhausted(db.records[item.key]),true);updateLedger(db,{...item,status:'Registrerad klar'});assert.equal(exhausted(db.records[item.key]),false);assert.ok(db.records[item.key].verifiedAt);assert.equal(db.events.length,4);});
function fixture(earnedAfter=Infinity){let stored={},runs=0;const pilot=new Autopilot({api:{storage:{local:{set:async value=>Object.assign(stored,structuredClone(value))}}},report:()=>{}});pilot.guard=async()=>{};pilot.navigate=async()=>{};pilot.inventory=async()=>({earned:runs>=earnedAfter,items:[{completed:true}]});pilot.crawlCatalog=async queue=>queue.push({key:'/home/content/view/1',url:'https://salescoach.apple.com/home/content/view/1',title:'Requirement',status:'Hittad'});pilot.processQueue=async queue=>{runs++;queue.forEach(i=>i.status='Registrerad klar');};const badge={key:'/home/achievements/unearned/2',url:'https://salescoach.apple.com/home/achievements/unearned/2',title:'Badge',kind:'badge',status:'Ej verifierad'};pilot.badges.set(badge.key,badge);return {pilot,badge,runs:()=>runs,stored:()=>stored};}
test('Badge gets three passes and remains unresolved despite completed children',async()=>{const f=fixture();await f.pilot.finishBadges([],async()=>{});assert.equal(f.runs(),3);assert.equal(f.stored().coachLedger.records[f.badge.key].attempts,3);assert.equal(f.stored().coachLedger.records[f.badge.key].status,'Behöver hjälp');await f.pilot.finishBadges([],async()=>{});assert.equal(f.runs(),3);});
test('Only actual earned status ends badge attempts early',async()=>{const f=fixture(2);await f.pilot.finishBadges([],async()=>{});assert.equal(f.runs(),2);assert.equal(f.stored().coachLedger.records[f.badge.key].status,'Registrerad klar');});
test('Resource exhausted in a previous run is not opened automatically',async()=>{const f=fixture();const item={key:'/home/content/view/1',url:'https://salescoach.apple.com/home/content/view/1',title:'Requirement',status:'Hittad'};f.pilot.ledger.records[item.key]={attempts:3,status:'Behöver hjälp',reason:'No progress'};f.pilot.navigate=async()=>assert.fail('Must not repeat resource');await Autopilot.prototype.processQueue.call(f.pilot,[item],async()=>{});assert.match(item.reason,/Tre genomgångar/);});
