import test from 'node:test';
import assert from 'node:assert/strict';
import {Autopilot,isTransientFrameError} from '../src/autopilot.js';

test('Transient Sales Coach frame removal is recognized and retried',async()=>{
 let calls=0;
 const api={scripting:{executeScript:async()=>{if(++calls<3)throw new Error('Frame with ID 0 was removed.');return [{result:true}];}},tabs:{get:async()=>({active:true,url:'https://salescoach.apple.com/home/for-you'})}};
 const messages=[];const p=new Autopilot({api,report:m=>messages.push(m),wait:async()=>{}});p.tabId=1;p.expectedURL='https://salescoach.apple.com/home/for-you';
 assert.equal(isTransientFrameError(new Error('Frame with ID 0 was removed.')),true);
 assert.deepEqual(await p.script({target:{tabId:1,frameIds:[0]}}),[{result:true}]);
 assert.equal(calls,3);assert.equal(messages.length,2);
});

test('Completion verification polls the parent until Sales Coach registers it',async()=>{
 let checks=0;const p=new Autopilot({api:{},report:()=>{},wait:async()=>{}});p.navigate=async()=>{};p.inventory=async()=>({earned:false,items:[{url:'https://salescoach.apple.com/home/content/view/42',completed:++checks===3}]});
 const verified=await p.verifyCompletion({title:'Moment',key:'/home/content/view/42',parents:['https://salescoach.apple.com/home/collection/1']},{attempts:3,delays:[0,0]});
 assert.equal(verified,true);assert.equal(checks,3);
});

test('A blocked video is marked as requiring one click while the queue continues',async()=>{
 const p=new Autopilot({api:{},report:()=>{},onPage:()=>{}});p.guard=async()=>{};p.navigate=async()=>{};p.inventory=async()=>({items:[]});p.frames=async()=>[{frameId:0,result:{lesson:'kursmaterial '.repeat(20),video:{ended:false}}}];p.resource=async()=>{const e=new Error('Tryck Play.');e.code='USER_GESTURE_REQUIRED';throw e;};
 const item={url:'https://salescoach.apple.com/home/content/view/7',key:'/home/content/view/7',title:'Video',parents:[]};await p.processQueue([item],async()=>{});
 assert.equal(item.status,'Behöver ett klick');assert.match(item.reason,/Play/);
});

test('Interactive reading pauses long enough for Sales Coach to register opened sections',async()=>{
 const waits=[];let opened=false;const p=new Autopilot({api:{},report:()=>{},wait:async()=>{}});p.frames=async()=>[{frameId:0,result:opened?{lesson:'text',sections:[],next:[],options:[],complete:true}:{lesson:'text',sections:['Avsnitt'],next:[],options:[]}}];p.act=async()=>{opened=true;};p.sleep=async ms=>waits.push(ms);
 await p.resource();assert.ok(waits.includes(3000));
});
test('Resource activates safe interactive content until an XP signal appears',async()=>{let clicked=false;const reports=[];const p=new Autopilot({api:{},report:m=>reports.push(m),wait:async()=>{}});p.frames=async()=>[{frameId:2,result:clicked?{lesson:'',sections:[],interactions:[],next:[],options:[],xp:10,success:false,complete:true}:{lesson:'',sections:[],interactions:[{id:1,text:'Visa exempel'}],next:[],options:[],xp:0,success:false,complete:false}}];p.act=async(_frame,action)=>{assert.equal(action,'interact');clicked=true;};p.sleep=async()=>{};assert.equal(await p.resource(),'passed');assert.equal(clicked,true);assert.ok(reports.some(m=>/erfarenhetspoäng/.test(m)));});
test('Resource scrolls through the page before accepting its XP confirmation',async()=>{let scrolled=false;const p=new Autopilot({api:{},report:()=>{},wait:async()=>{}});p.frames=async()=>[{frameId:2,result:scrolled?{lesson:'',sections:[],interactions:[],scroll:[],next:[],options:[],xp:5,success:false,complete:true}:{lesson:'',sections:[],interactions:[],scroll:[{id:1,top:0,remaining:900}],next:[],options:[],xp:0,success:false,complete:false}}];p.act=async(_frame,action)=>{assert.equal(action,'scroll');scrolled=true;};p.sleep=async()=>{};assert.equal(await p.resource(),'passed');assert.equal(scrolled,true);});
test('Resource opens nested sections and an internal subpage before accepting XP',async()=>{let stage=0;const actions=[];const states=[{sections:['Huvuddel'],sectionControls:[{id:1,text:'Huvuddel'}],next:[]},{sections:['Detaljer'],sectionControls:[{id:2,text:'Detaljer'}],next:[]},{sections:[],sectionControls:[],next:['Nästa'],stepControls:[{id:1,text:'Nästa'}]},{sections:[],sectionControls:[],next:[],xp:8,success:false,complete:true}];const p=new Autopilot({api:{},report:()=>{},wait:async()=>{}});p.frames=async()=>[{frameId:2,result:{lesson:'',interactions:[],scroll:[],options:[],xp:0,success:false,complete:false,...states[stage]}}];p.act=async(_frame,action)=>{actions.push(action);stage++;};p.sleep=async()=>{};assert.equal(await p.resource(),'passed');assert.deepEqual(actions,['expand','expand','next']);});

test('Run this page includes course requirements from a specialist collection',async()=>{
 const collection='https://salescoach.apple.com/home/collection/245263',course='https://salescoach.apple.com/home/course/35019';let received=[];const p=new Autopilot({api:{tabs:{query:async()=>[{id:1,url:collection}]}},report:()=>{},onPage:()=>{}});p.inventory=async()=>({url:collection,earned:false,items:[{title:'iPhone—utöka möjligheterna',url:course,completed:false,locked:false}]});p.processQueue=async queue=>{received=queue;queue[0].status='Åtkomst saknas';queue[0].reason='Kräver eventinbjudan.';};p.navigate=async()=>{};
 await assert.rejects(p.start(),/eventinbjudan/);assert.equal(received[0].key,'/home/course/35019');
});
test('Unfinished work is persisted and cleared only after verification',async()=>{const storage={};const api={storage:{local:{get:async()=>storage,set:async value=>Object.assign(storage,value)}}};const p=new Autopilot({api,report:()=>{}});await p.rememberIssue({key:'/home/course/9',url:'https://salescoach.apple.com/home/course/9',title:'Workshop',status:'Åtkomst saknas',reason:'Kräver inbjudan.'});assert.equal(storage.autopilotIssues[0].status,'Åtkomst saknas');assert.equal(storage.autopilotIssues[0].attempts,1);const restored=new Autopilot({api,report:()=>{}});await restored.loadIssues();assert.equal(restored.issues.get('/home/course/9').reason,'Kräver inbjudan.');await restored.clearIssue('/home/course/9');assert.deepEqual(storage.autopilotIssues,[]);});
test('Existing unresolved queue entries migrate into the persistent issue log',async()=>{const storage={autopilotQueue:[{key:'/home/course/4',url:'https://salescoach.apple.com/home/course/4',title:'Event',status:'Åtkomst saknas',reason:'Inbjudan krävs.'},{key:'/home/content/view/5',status:'Registrerad klar'}]};const api={storage:{local:{get:async()=>storage,set:async value=>Object.assign(storage,value)}}};const p=new Autopilot({api,report:()=>{}});await p.loadIssues();assert.equal(p.issues.size,1);assert.equal(storage.autopilotIssues[0].key,'/home/course/4');});
test('A remembered invitation requirement is skipped without reopening the page',async()=>{const p=new Autopilot({api:{storage:{local:{set:async()=>{}}}},report:()=>{},onPage:()=>{}});p.guard=async()=>{};p.issues.set('/home/course/9',{key:'/home/course/9',status:'Åtkomst saknas',reason:'Kräver inbjudan.'});let navigated=false;p.navigate=async()=>{navigated=true;};const item={key:'/home/course/9',url:'https://salescoach.apple.com/home/course/9',title:'Workshop',status:'Hittad'};await p.processQueue([item],async()=>{});assert.equal(navigated,false);assert.equal(item.status,'Åtkomst saknas');});
test('A prepared quiz guide is persisted and skipped until the user opens it',async()=>{const storage={};const api={storage:{local:{get:async()=>storage,set:async value=>Object.assign(storage,value)}}};const guide=[{prompt:'Fråga',suggestions:['Svar'],reason:'Förklaring',evidence:'Källa'}],p=new Autopilot({api,report:()=>{},onPage:()=>{}});await p.rememberIssue({key:'/home/content/view/8',title:'Prov',status:'Besvara provet',reason:'Väntar på dig.',studyGuide:guide});const restored=new Autopilot({api,report:()=>{},onPage:()=>{}});await restored.loadIssues();restored.guard=async()=>{};let navigated=false;restored.navigate=async()=>{navigated=true;};const item={key:'/home/content/view/8',url:'https://salescoach.apple.com/home/content/view/8',title:'Prov',status:'Hittad'};await restored.processQueue([item],async()=>{});assert.equal(navigated,false);assert.equal(item.status,'Besvara provet');assert.deepEqual(item.studyGuide,guide);});
