import {queueProgress,duration} from './run-progress.js';
import {checkUpdate,RELEASES} from './updates.js';
import {nativeRequest} from './native.js';
import React,{useState,useRef,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {extractPage,expandReadSection,mergeFrames,isCoachURL,relevantContext,indexContext} from './extract.js';
import {Autopilot,validateAnswer} from './autopilot.js';
const demo=!globalThis.chrome?.runtime?.id;
const issueStatuses=new Set(['Ej verifierad','Behöver hjälp','Behöver ett klick','Behöver dina uppgifter','Åtkomst saknas']);
const sample={title:'Säljstrategi – modernisera fälttjänster',url:'https://salescoach.apple.com/home/achievements/unearned/29594',text:'Fältteam behöver tillgång till arbetsorder och kundhistorik. iPhone och iPad kan ge tekniker information på plats och kontakt med experter. Digitala underskrifter kan dokumentera kundens godkännande.',items:[{title:'Säljstrategi – modernisera fälttjänster',completed:true},{title:'Handledning för fälttjänster',completed:false},{title:'Apple-enheter är byggda för kompatibilitet',completed:false},{title:'Driftsättning och hantering',completed:true},{title:'Smarta investeringar',completed:true}],frameCount:2,capturedAt:Date.now()};
function App(){
 const [runState,setRunState]=useState({mode:'idle',phase:'Redo att starta',started:0,heartbeat:0,changed:0}),[now,setNow]=useState(Date.now());
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);
 function updateRun(data){setRunState(old=>({...old,...data,changed:data.phase&&data.phase!==old.phase?Date.now():old.changed}));}

 const [academyNotice,setAcademyNotice]=useState(''),[issues,setIssues]=useState([]);
 const [personalDrafts,setPersonalDrafts]=useState({});
 const currentVersion=demo?'0.5.0':chrome.runtime.getManifest().version;
 const [update,setUpdate]=useState(null),[updateError,setUpdateError]=useState(''),[checking,setChecking]=useState(false);
 async function refreshUpdate(force=false){if(demo)return;setChecking(true);setUpdateError('');try{setUpdate(await checkUpdate({current:currentVersion,storage:chrome.storage.local,force}));}catch(e){setUpdateError(e.message);}finally{setChecking(false);}}
 useEffect(()=>{refreshUpdate();},[]);

 const [page,setPage]=useState(demo?sample:null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[ai,setAI]=useState(demo?'Demoläge – AI inte ansluten':'Inte kontrollerad'),[answer,setAnswer]=useState(''),[question,setQuestion]=useState(''),[source,setSource]=useState(null),[frames,setFrames]=useState([]),[history,setHistory]=useState([]),[tabID,setTabID]=useState(null);
 const nativeAbort=useRef(null);const pilot=useRef(null);const [queue,setQueue]=useState([]);const [auto,setAuto]=useState(false),[log,setLog]=useState([]);
 useEffect(()=>()=>{pilot.current?.stop();nativeAbort.current?.abort();},[]);
 useEffect(()=>{if(demo)return;chrome.storage.local.get(['academyNotice','autopilotIssues','autopilotQueue']).then(async s=>{setAcademyNotice(s.academyNotice||'');let rows=s.autopilotIssues||[];if(!rows.length){const now=Date.now();rows=(s.autopilotQueue||[]).filter(i=>i?.key&&issueStatuses.has(i.status)).map(i=>({...i,firstSeen:now,lastSeen:now,attempts:1}));if(rows.length)await chrome.storage.local.set({autopilotIssues:rows});}setIssues(rows);});const listener=(changes,area)=>{if(area!=='local')return;if(changes.academyNotice)setAcademyNotice(changes.academyNotice.newValue||'');if(changes.autopilotIssues)setIssues(changes.autopilotIssues.newValue||[]);};chrome.storage.onChanged.addListener(listener);return()=>chrome.storage.onChanged.removeListener(listener);},[]);
 useEffect(()=>{if(demo)return;chrome.storage.local.get('autopilotQueue').then(s=>setQueue(s.autopilotQueue||[]));},[]);
 useEffect(()=>{
  if(demo||busy)return;let cancelled=false,reading=false,last='';
  async function refresh(){if(reading||cancelled)return;reading=true;try{const t=await active();const r=await chrome.scripting.executeScript({target:{tabId:t.id,allFrames:true},func:extractPage});const p=mergeFrames(r);const key=JSON.stringify([p.url,p.text,p.items]);if(!cancelled&&last!==key){last=key;setPage(p);setTabID(t.id);setAnswer('');setSource(null);setFrames([...new Set(r.flatMap(f=>f.result?.frames||[]).map(u=>new URL(u).origin+'/*'))].filter(o=>o!=='https://salescoach.apple.com/*'));}}catch{}finally{reading=false;}}
  refresh();const timer=setInterval(refresh,2500);return()=>{cancelled=true;clearInterval(timer);};
 },[busy]);
 function report(text){updateRun({phase:text,heartbeat:Date.now(),media:null});setLog(rows=>[...rows,{at:Date.now(),text}].slice(-40));}
 async function startAuto(discover=false){setAuto(true);setQueue([]);setLog([]);setRunState({mode:'running',phase:'Startar…',started:Date.now(),heartbeat:Date.now(),changed:Date.now()});await run(async()=>{const runner=new Autopilot({api:chrome,native,report,onPage:setPage,onQueue:setQueue,onStatus:updateRun});pilot.current=runner;try{await (discover?runner.discoverAndRun():runner.start());updateRun({mode:'finished',ended:Date.now(),phase:'Körningen avslutad – se registrerade och återstående moment.'});}catch(e){report(e.message);updateRun({mode:runner.stopped?'stopped':'error',ended:Date.now()});throw e;}finally{pilot.current=null;setAuto(false);}});}
 function stopAuto(){updateRun({mode:'stopping'});pilot.current?.stop();nativeAbort.current?.abort();report('Stoppar – inga nya åtgärder skickas. Ett pågående AI-anrop kan behöva avslutas.');}
 async function run(fn){setBusy(true);setNotice('');try{await fn();}catch(e){setNotice(e.message || String(e));}finally{setBusy(false);}}
 async function active(){const [t]=await chrome.tabs.query({active:true,currentWindow:true});if(!t?.id||!isCoachURL(t.url))throw new Error('Öppna en sida på salescoach.apple.com och försök igen.');return t;}
 async function scan(){if(demo){setPage(sample);setNotice('Exempeldata. Ingen anslutning till Sales Coach.');return;}
  const t=await active();const result=await chrome.scripting.executeScript({target:{tabId:t.id,allFrames:true},func:extractPage});const p=mergeFrames(result);
  setPage(p);setTabID(t.id);setAnswer('');setSource(null);setFrames([...new Set(result.flatMap(f=>f.result?.frames||[]).map(u=>new URL(u).origin+'/*'))].filter(o=>o!=='https://salescoach.apple.com/*'));
  const entry={title:p.title,url:p.url,completed:p.items.filter(i=>i.completed).length,total:p.items.length,earned:p.earned,at:Date.now()};
  const stored=await chrome.storage.local.get('history');const rows=[entry,...(stored.history||[])].slice(0,40);await chrome.storage.local.set({history:rows});setHistory(rows.slice(0,4));
 }
 async function native(payload){if(pilot.current)updateRun({phase:'Väntar på lokal Apple Intelligence (högst 90 sekunder)',media:null});if(demo)throw new Error('AI kräver tillägget och den installerade Mac-bryggan.');const controller=new AbortController();nativeAbort.current=controller;try{return await nativeRequest(chrome.runtime,payload,{signal:controller.signal});}finally{if(nativeAbort.current===controller)nativeAbort.current=null;}}
 async function status(){const r=await native({action:'status'});setAI(r.message||r.error||'Okänd status');if(!r.ok)return;setAI('Testar ett strukturerat svar lokalt…');const context=indexContext('MDM gör att organisationen kan konfigurera och hantera sina enheter centralt. MDM kan distribuera appar och inställningar till företagets enheter.');const reply=await native({action:'choose',context,optionCount:2,requiredCount:1,question:'Vad används MDM till? 1. Hantera enheter. 2. Ladda batteriet. Exakt ett alternativ ska väljas.'});if(!reply.ok){setAI('AI-testet misslyckades');throw new Error(reply.error||reply.message);}const result=validateAnswer(reply.text,{options:[{id:1},{id:2}],multi:false},context);if(result.ids.join(',')!=='1')throw new Error('AI-testet valde fel alternativ.');setAI('Apple Intelligence redo · strukturerat svar testat');}
 async function generate(mode){if(!page)throw new Error('Läs in en sida först.');if(mode==='answer'&&!question.trim())throw new Error('Skriv eller klistra in frågan och svarsalternativen.');if(!demo){const t=await active();if(t.id!==tabID||t.url!==page.url)throw new Error('Sidan har ändrats. Läs in den på nytt innan du ber om ett förslag.');}
  const context=relevantContext(page.text,mode==='answer'?question:'');setSource({title:page.title,url:page.url,context,limited:context.length<page.text.length});const r=await native({action:mode,context,question:question.slice(0,2000)});if(!r.ok)throw new Error(r.error||r.message);setAnswer(r.text);}
 async function open(item){if(demo){setNotice('Navigation är avstängd i demovyn.');return;}if(item.locked||!isCoachURL(item.url))throw new Error('Resursen kan inte öppnas.');const t=await active();await chrome.tabs.update(t.id,{url:item.url});setNotice('Resursen öppnad. Panelen uppdateras automatiskt.');}
 async function retryIssue(item){const updated=issues.map(i=>i.key===item.key?{...i,retryRequested:true}:i);await chrome.storage.local.set({autopilotIssues:updated});setIssues(updated);await open(item);setNotice('Momentet är öppnat och kommer att kontrolleras igen vid nästa autopilotkörning.');}
 async function expand(){if(demo){setNotice('I tillägget öppnas ett läsavsnitt åt gången.');return;}const t=await active();const r=await chrome.scripting.executeScript({target:{tabId:t.id,allFrames:true},func:expandReadSection});setNotice(r.some(x=>x.result?.opened)?'Läsavsnitt öppnat. Läs in sidan igen när innehållet har laddats.':'Inga fler läsavsnitt hittades i de åtkomliga ramarna.');}
 const qp=queueProgress(queue);
 const activeRun=['running','stopping'].includes(runState.mode);
 const silent=activeRun&&now-runState.heartbeat>15000;
 const done=page?.progress?.completed??(page?.items.filter(i=>i.completed).length||0),total=page?.progress?.total??(page?.items.length||0);
 return <main><header><div className="brand">a<span>tea</span><small>COACH PILOT</small></div><span className="local"><i/> Lokalt på din Mac</span></header>
 <section className={'run-status '+(activeRun?'is-running':'')} aria-label="Pilotens körstatus"><div className="row"><strong><span className="run-dot"/>{({idle:'Inte igång',running:'Kör',stopping:'Stoppar…',finished:'Avslutad',stopped:'Stoppad',error:'Pausad – behöver hjälp'})[runState.mode]}</strong><span>{runState.started?duration(((runState.ended||now)-runState.started)/1000):''}</span></div><p className="run-phase" role="status">{runState.phase}</p>{activeRun&&qp.current&&<p className="small">Aktuellt moment: {qp.current}</p>}{activeRun&&<p className="small">Detta steg: {duration((now-runState.changed)/1000)} · Senaste återkoppling: {Math.max(0,Math.floor((now-runState.heartbeat)/1000))} s sedan</p>}
 {qp.total>0?<><progress max={qp.total} value={qp.processed} aria-label="Genomgångna moment"/><p className="small">{qp.processed}/{qp.total} hittade moment genomgångna · {qp.complete} registrerade klara · {qp.needsHelp} behöver uppföljning. Antalet växer medan piloten söker vidare.</p></>:activeRun?<><progress aria-label="Arbetar – antal moment ännu okänt"/><p className="small">{runState.media?'Videon bearbetas.':'Söker nästa moment. Totalt antal är okänt; körningen börjar så snart ett moment hittas.'}</p></>:<p className="small">{queue.length?'Sparad kö – ingen körning pågår.':'Starta med Hitta och kör automatiskt eller Kör denna sida.'}</p>}
 {activeRun&&runState.media&&<><p className="small">Video: {duration(runState.media.time)} / {runState.media.duration?duration(runState.media.duration):'okänd längd'}</p>{runState.media.duration>0&&<progress max={runState.media.duration} value={runState.media.time} aria-label="Videons uppspelning"/>}</>}
 {silent&&<p className="notice">Ingen ny återkoppling på {Math.floor((now-runState.heartbeat)/1000)} sekunder. Ett anrop kan fortfarande pågå. Du kan stoppa körningen nedan.</p>}{activeRun&&<button className="stop" disabled={runState.mode==='stopping'} onClick={stopAuto}>Stoppa körningen</button>}</section>
 <div className="intro"><p className="eyebrow">DITT NÄSTA STEG</p><h1>Lär dig mer.<br/><span>Håll koll på resan.</span></h1><p>Samla återstående moment och få stöd från kursmaterialet.</p></div>
 {demo&&<div className="banner">DEMOVY · Exempeldata, inga ändringar i Sales Coach.</div>}
 <section className="autopilot"><div className="row"><h2>Autopilot</h2><span className="pill">BETA</span></div><p className="muted">Öppnar moment, rullar genom hela sidan, går igenom relevanta flikar och interaktioner, läser avsnitt, spelar videor och väljer och skickar in svar på flervalsfrågor. Prioriterar Apple Professional Academy och dess undersamlingar först, därefter övrigt under För dig. Piloten letar efter Sales Coach-bekräftelse som 100 %, slutfört eller intjänade erfarenhetspoäng innan den går vidare.</p><div className="actions"><button className="primary" disabled={demo||busy} onClick={()=>startAuto(true)}>Hitta och kör automatiskt</button><button disabled={demo||busy} onClick={()=>startAuto(false)}>Kör denna sida</button><button className="stop" disabled={!auto} onClick={stopAuto}>Stoppa</button></div><p className="small">Behåll Sales Coach-fliken aktiv. Moment som inte kan lösas läggs under Behöver hjälp. Övriga Academy-moment fortsätter, sedan fortsätter piloten med annat material om Academy inte går att slutföra. Ett AI-förslag kan vara fel även när det har ett källcitat.</p>{queue.length>0&&<details open><summary>Kö · {queue.length} resurser</summary><ul className="autolog">{queue.map(item=><li key={item.key}><strong>{item.academy?'Academy · ':''}{item.status}</strong> · {item.title}{item.reason&&<div className="small">{item.reason}</div>}{item.status==='Behöver ett klick'&&<button disabled={busy} onClick={()=>run(async()=>{await open({...item,url:item.url||'https://salescoach.apple.com'+item.key});setNotice('Tryck Play i Sales Coach. När videon rör sig kan du starta autopiloten igen.');})}>Öppna video och tryck Play</button>}</li>)}</ul></details>}{log.length>0&&<ol className="autolog" aria-live="polite">{log.map((entry,i)=><li key={i}><time>{new Date(entry.at).toLocaleTimeString('sv-SE')}</time> {entry.text}</li>)}</ol>}</section>
 {academyNotice&&<section role="status"><h2>Academy väntar</h2><p>{academyNotice}</p><p className="small">Academy kontrolleras på nytt nästa gång du startar automatisk sökning.</p></section>}
 {issues.length>0&&<section className="remaining" aria-label="Sparad uppföljningslista"><div className="row"><h2>Återstår · {issues.length}</h2><span className="pill">SPARAD LOKALT</span></div><p className="muted">Ofärdiga moment sparas mellan körningar. Inbjudningskrav och personliga uppgifter hoppas över tills du väljer att kontrollera dem igen.</p><ul className="resources">{issues.map(item=><li key={item.key}><span className="check">!</span><span><strong>{item.status}</strong><br/>{item.title}<small>{item.reason}</small>{item.inputQuestion&&<small><strong>Din uppgift:</strong> {item.inputQuestion}</small>}</span><button disabled={busy} onClick={()=>run(()=>retryIssue(item))}>{item.status==='Behöver dina uppgifter'?'Öppna och svara ↗':'Öppna och kontrollera ↗'}</button></li>)}</ul></section>}
 {queue.filter(i=>i.status==='Behöver dina uppgifter').length>0&&<section className="personal-input"><h2>Behöver dina uppgifter</h2><p>De här momenten väntar på dig. Övriga Academy-moment kan fortsätta.</p>{queue.filter(i=>i.status==='Behöver dina uppgifter').map(item=><article key={item.key}><h3>{item.title}</h3><label htmlFor={'personal-'+item.key.split('/').pop()}>{item.inputQuestion}</label><textarea id={'personal-'+item.key.split('/').pop()} value={personalDrafts[item.key]||''} onChange={e=>setPersonalDrafts(d=>({...d,[item.key]:e.target.value}))} placeholder="Skriv ett utkast med dina egna uppgifter…" maxLength={8000}/><div className="actions"><button disabled={busy} onClick={()=>run(async()=>{if(!/^\/home\/content\/view\/\d+$/.test(item.key))throw new Error('Ogiltigt moment.');const t=await active();if(personalDrafts[item.key])await navigator.clipboard.writeText(personalDrafts[item.key]);await chrome.tabs.update(t.id,{url:'https://salescoach.apple.com'+item.key});setNotice('Fyll i och skicka formuläret i Sales Coach. Ditt utkast är kopierat om du skrev ett. Starta sedan Hitta och kör automatiskt igen.');})}>{personalDrafts[item.key]?'Kopiera utkast och öppna formuläret':'Öppna och svara'}</button></div><p className="small">Utkastet sparas inte och försvinner när panelen stängs. Det skickas inte till AI. Granska och skicka svaren i Sales Coach; piloten kontrollerar registreringen vid nästa körning.</p></article>)}</section>}
 <section><div className="row"><h2>Aktuell prestation</h2><button className="text" disabled={busy} onClick={()=>run(scan)}>↻ Uppdatera</button></div>
 {page?<><h3>{page.title}</h3>{total>0?<><div className="progress"><span style={{width:`${done/total*100}%`}}/></div><div className="row muted"><span>{done} av {total} registrerade som klara</span><span>{Math.round(done/total*100)}%</span></div></>:<p className="muted">{page.earned?'Märket är registrerat som taget.':'Läsresurs · Slutförandestatus kontrolleras på prestationssidan.'}</p>}
 <ul className="resources">{page.items.map((i,n)=><li key={i.url||n}><span className={'check '+(i.completed?'done':'')}>{i.completed?'✓':i.locked?'−':String(n+1).padStart(2,'0')}</span><span>{i.title}</span>{!i.completed&&<button disabled={busy||i.locked} onClick={()=>run(()=>open(i))}>{i.locked?'Låst':'Öppna ↗'}</button>}</li>)}</ul><p className="small">Avläst {new Date(page.capturedAt).toLocaleTimeString('sv-SE')} · {page.frameCount} åtkomliga ramar. Visar bara den inlästa sidan.</p><button className="secondary" disabled={busy} onClick={()=>run(expand)}>Öppna nästa läsavsnitt</button></>:<p className="muted">Sales Coach läses in automatiskt när sidopanelen är öppen.</p>}
 {frames.length>0&&<button className="text" disabled={busy} onClick={()=>run(async()=>{const granted=await chrome.permissions.request({origins:frames});setNotice(granted?'Ramåtkomst beviljad. Läs in sidan igen.':'Ramåtkomst nekad. Du kan fortfarande klistra in kursunderlag nedan.');})}>Tillåt kursramar ({frames.map(f=>new URL(f).hostname).join(', ')})</button>}
 </section>
 <section><div className="row"><h2>Din lokala studiecoach</h2><span className="pill">APPLE INTELLIGENCE</span></div><p className="muted">{ai}</p><button className="text" disabled={busy} onClick={()=>run(status)}>Kontrollera AI-anslutning →</button>
 <label htmlFor="q">Fråga och svarsalternativ</label><textarea id="q" value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Klistra in frågan du vill förstå…" maxLength={2000}/><div className="actions"><button className="primary" disabled={busy||!page} onClick={()=>run(()=>generate('answer'))}>Föreslå och förklara</button><button className="secondary" disabled={busy||!page} onClick={()=>run(()=>generate('summary'))}>Sammanfatta</button></div>
 <details><summary>Granska eller komplettera kursunderlaget</summary><p className="small">Endast detta underlag och din fråga skickas till den lokala modellen. Ta bort personuppgifter. Kursinnehåll sparas inte i historiken.</p><textarea className="context" aria-label="Kursunderlag" value={page?.text||''} onChange={e=>{setPage(p=>({...p,text:e.target.value}));setAnswer('');}} disabled={!page}/></details>
 {busy&&<p className="working" role="status">Arbetar…</p>}{notice&&<p className="notice" role="status">{notice}</p>}
 {answer&&<article className="answer"><p className="eyebrow">FÖRSLAG ATT GRANSKA</p><p>{answer}</p><details><summary>Underlag: {source?.title}</summary><p className="small">{source?.limited?'Ett urval av kursunderlaget användes.':'Hela det inlästa underlaget användes.'}</p><pre>{source?.context}</pre></details><button className="text" onClick={()=>run(async()=>{await navigator.clipboard.writeText(answer);setNotice('Förslaget kopierat.');})}>Kopiera förslag</button></article>}
 <p className="small">I manuellt läge granskar och skickar du in svaren själv. När autopiloten är startad väljer och skickar den in stödda flervalsfrågor automatiskt.</p></section>
 {history.length>0&&<section><div className="row"><h2>Senast kontrollerat</h2><button className="text" onClick={()=>run(async()=>{await chrome.storage.local.remove('history');setHistory([]);})}>Rensa</button></div>{history.map((h,n)=><p className="small" key={n}>{h.title} · {h.earned?'Märke taget':`${h.completed}/${h.total}`}</p>)}</section>}
 <section className="updates"><div className="row"><h2>Uppdateringar</h2><span className="pill">v{currentVersion}</span></div>
 <p role="status">{checking?'Kontrollerar GitHub…':updateError|| (update?.available?`Version ${update.version} finns att hämta.`:update?'Du har senaste versionen eller en nyare utvecklingsversion.':'')}</p>
 <div className="actions"><button disabled={demo||checking} onClick={()=>refreshUpdate(true)}>Sök uppdatering</button><a href={update?.url||RELEASES+'/latest'} target="_blank" rel="noopener noreferrer">{update?.available?'Hämta uppdatering ↗':'Öppna nedladdningar ↗'}</a></div>
 <p className="small">Öppna ZIP-paketets installationsapp och installera. Välj sedan Läs in igen för Coach Pilot i Edge och ladda om Sales Coach. Uppdatera när autopiloten är stoppad.</p>
 <p className="small">Kontrollerar GitHub när panelen öppnas, högst var 12:e timme. Inga kursfrågor eller svar skickas.</p></section>
 <footer>Oberoende pilot · Inte en officiell Apple- eller Atea-produkt<br/>Ingen moln-AI. Ingen avgift per token.</footer></main>;
}
createRoot(document.getElementById('root')).render(<App/>);
